Repository evidentlyai/evidently, pull requests merged in 2022-10, with the labels that each got.

#358 Add anderson in statistical test options
  docs/book/customization/options-for-statistical-tests.md
Labels: documentation, hacktoberfest

#352 added hellinger_distance for drift detection
  src/evidently/calculations/stattests/hellinger_distance.py
  src/evidently/calculations/stattests/utils.py
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#356 Add Cramér-von-mises test
  src/evidently/calculations/stattests/cramer_von_mises_stattest.py
  tests/stattests/test_stattests.py
Labels: enhancement, good first issue, hacktoberfest

#365 update Cramer-Von-Mises doc
  docs/book/customization/options-for-statistical-tests.md
Labels: documentation, hacktoberfest

#379 Add CVM in examples
  examples/how_to_questions/how_to_specify_stattest_for_a_testsuite.ipynb
  src/evidently/calculations/stattests/__init__.py
Labels: hacktoberfest

#364 added hellinger_distance unittest and updated doc
  docs/book/customization/options-for-statistical-tests.md
  src/evidently/calculations/stattests/hellinger_distance.py
  tests/stattests/test_stattests.py
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#380 Mann-Whitney U-rank drift test
  docs/book/customization/options-for-statistical-tests.md
  src/evidently/calculations/stattests/__init__.py
  src/evidently/calculations/stattests/mann_whitney_urank_stattest.py
  tests/stattests/test_stattests.py
Labels: enhancement, hacktoberfest

#371 fix for issue #334 feel zeroes of stattests utils
  src/evidently/calculations/stattests/utils.py
Labels: bug, hacktoberfest

#363 added Epps-Singleton test
  docs/book/customization/options-for-statistical-tests.md
  src/evidently/calculations/stattests/__init__.py
  src/evidently/calculations/stattests/epps_singleton_stattest.py
  tests/stattests/test_stattests.py
Labels: enhancement, hacktoberfest
